[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/cinder.mp4"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#dd8f74"
TimeTextColor="#f7dfc2"

FormBackgroundColor="#0a0605"

LoginFieldBackgroundColor="#170a0d"
PasswordFieldBackgroundColor="#170a0d"

LoginFieldTextColor="#f5cdb8"
PasswordFieldTextColor="#f5cdb8"

PlaceholderTextColor="#b98268"

LoginButtonTextColor="#0c211f"
LoginButtonBackgroundColor="#3fa9a0"

SystemButtonsIconsColor="#f0cf9e"
EnvironmentButtonTextColor="#f0cf9e"

DropdownTextColor="#f5ecd9"
DropdownSelectedTextColor="#0c211f"
DropdownBackgroundColor="#0d0705"
DropdownSelectedBackgroundColor="#3fa9a0"
DropdownBorderColor="#5a3a28"
DropdownSelectedBorderColor="#dcb85c"

HoverLoginButtonBackgroundColor="#6fc4bc"
HoverSystemButtonsIconsColor="#d97b4f"
HoverEnvironmentButtonTextColor="#d97b4f"

Blur="0.0"
FormPosition="left"
